### ISSUE TITLE
confirming that time: can be a Time object (Time.now)

### ISSUE THREAD

**Issue by angelacode** [toothrot/amplitude-api#15]
The documentation for amplitude say time is in milliseconds I believe, but the example in the docs shows Time.now which is a time object. 

I wanted to make sure this was correct.

**Comment by toothrot** [comment]
Sorry for the delayed response. I was out of the country!

I'll update the documentation. Right now, you should use a Time object. I'll try to resolve that with #10 and make this all less confusing.

**Comment by kolorahl** [comment]
This issue can be closed now; confirmed that at least version `0.0.10` works with either format. If you pass in a Time object it is converted to milliseconds since the Unix epoch. If you pass in an integer (or anything else that responds to `to_i`) it assumes that _seconds_ since the Unix epoch has been supplied and will multiply it by 1,000 to get to _milliseconds_ since the Unix epoch.
